name: Docker Image

on:
  push:
    branches: [ develop ]

env:
  APP_NAME_BACKEND: 'dimdim-backend'
  APP_NAME_FRONTEND: 'dimdim-frontend'

jobs:
    backend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build backend and push
          uses: docker/build-push-action@v2
          with:
            context: '../../applications/dimdim-backend/Dockerfile'
            push: true
            tags: slashicorp/${{ env.APP_NAME_BACKEND }}:$GITHUB_RUN_ID

    frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build frontend and push
          uses: docker/build-push-action@v2
          with:
            context: '../../applications/dimdim-frontend/Dockerfile'
            push: true
            tags: slashicorp/${{ env.APP_NAME_FRONTEND }}:$GITHUB_RUN_ID